[package]
name = "rusty-mqtt"
version = "0.1.0"
authors = ["Leonardo Razovic <leorazzo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.48"
log = "0.4.8"
env_logger = "0.7.1"
uuid = { version = "0.8.1", features = ["v4"] }
clap = "2.33.0"
